# Generated by Django 2.2.2 on 2019-07-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20190702_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.ImageField(upload_to='gallery', verbose_name='Изображение'),
        ),
    ]
